# Generated by Django 6.0 on 2026-01-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('waste_type', models.CharField(choices=[('plastic', '♻️ Plastic'), ('paper', '📦 Paper'), ('organic', '🍌 Organic / Wet Waste'), ('metal', '🔩 Metal'), ('glass', '🧴 Glass'), ('e_waste', '💻 E-Waste'), ('medical', '🏥 Medical Waste'), ('construction', '🧱 Construction Waste'), ('other', '❓ Other')], max_length=20)),
                ('waste_type_other', models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=100)),
                ('quantity_type', models.CharField(choices=[('small', 'Small (1–2 kg)'), ('medium', 'Medium (3–10 kg)'), ('large', 'Large (10+ kg)')], max_length=10)),
                ('exact_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Exact quantity in kg', max_digits=8, null=True)),
                ('waste_condition', models.CharField(blank=True, choices=[('dry', 'Dry'), ('wet', 'Wet'), ('mixed', 'Mixed'), ('hazardous', 'Hazardous')], max_length=20)),
                ('image', models.ImageField(help_text='Upload waste photo', upload_to='waste_reports/')),
                ('location_auto', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('collected', 'Collected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
