# Generated by Django 6.0 on 2026-01-06 02:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_wastereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('shop_name', models.CharField(max_length=300)),
                ('shop_type', models.CharField(choices=[('scrap_dealer', 'Scrap Dealer'), ('recycling_center', 'Recycling Center'), ('waste_collector', 'Waste Collector'), ('junkyard', 'Junkyard'), ('ewaste_handler', 'E-Waste Handler'), ('other', 'Other')], max_length=50)),
                ('waste_categories_handled', models.JSONField(default=list, help_text='List of waste categories this buyer handles')),
                ('shop_address', models.TextField()),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='buyer_shops/')),
                ('aadhaar_number', models.CharField(help_text='Encrypted Aadhaar number', max_length=500)),
                ('aadhaar_last_4', models.CharField(help_text='Last 4 digits for display', max_length=4)),
                ('trade_license', models.FileField(help_text='Upload trade license/business registration', upload_to='buyer_licenses/')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer',
                'verbose_name_plural': 'Buyers',
                'ordering': ['-created_at'],
            },
        ),
    ]
