# Generated by Django 6.0 on 2026-01-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='trade_license',
            field=models.FileField(blank=True, help_text='Upload trade license/business registration (optional)', null=True, upload_to='buyer_licenses/'),
        ),
    ]
