# Generated by Django 6.0 on 2026-01-06 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_buyer_trade_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('offered_price', models.DecimalField(decimal_places=2, help_text='Price offered by buyer in ₹', max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Message from buyer to user')),
                ('user_response_message', models.TextField(blank=True, help_text='Message from user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='mainapp.buyer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('waste_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='mainapp.wastereport')),
            ],
            options={
                'verbose_name': 'Pickup Request',
                'verbose_name_plural': 'Pickup Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
