# Generated by Django 6.0 on 2026-01-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_buyerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='confirmed_pickup_time',
            field=models.DateTimeField(blank=True, help_text='Confirmed pickup time by user', null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='proposed_time_slot_1',
            field=models.DateTimeField(blank=True, help_text='First proposed pickup time by buyer', null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='proposed_time_slot_2',
            field=models.DateTimeField(blank=True, help_text='Second proposed pickup time by buyer', null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='proposed_time_slot_3',
            field=models.DateTimeField(blank=True, help_text='Third proposed pickup time by buyer', null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
