# Generated by Django 6.0 on 2026-01-07 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_pickuprequest_confirmed_pickup_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(help_text='Username at time of pickup', max_length=150)),
                ('buyer_shop_name', models.CharField(help_text='Shop name at time of pickup', max_length=200)),
                ('waste_type', models.CharField(help_text='Type of waste collected', max_length=50)),
                ('quantity', models.CharField(help_text='Quantity collected', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Pickup location', max_length=500)),
                ('offered_price', models.DecimalField(decimal_places=2, help_text='Final price paid', max_digits=10)),
                ('reported_at', models.DateTimeField(help_text='When waste was originally reported')),
                ('scheduled_at', models.DateTimeField(help_text='When pickup was scheduled')),
                ('completed_at', models.DateTimeField(help_text='When pickup was completed')),
                ('pickup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='mainapp.pickuprequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pickup History',
                'verbose_name_plural': 'Pickup Histories',
                'ordering': ['-completed_at'],
            },
        ),
    ]
