# Generated by Django 6.0 on 2026-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_pickuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='confirmed_pickup_address',
            field=models.TextField(blank=True, help_text='Final confirmed pickup address'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='full_address',
            field=models.TextField(blank=True, help_text='Complete pickup address with house/flat number, street, etc.'),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
