# Generated by Django 4.2.27 on 2026-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_pickuprequest_confirmed_pickup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='wastereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
        ),
    ]
