# Generated by Django 4.2.27 on 2026-01-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_wastereport_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
